CDCgov/data-exchange-portal

.gitignore
README.md
api/package-lock.json
api/package.json
package.json
staticwebapp.config.json
yarn.lock

Initial release of the dex portal.
Changelog:
- Initial iteration of the user auth flow with SAMS and OAuth token grant
- Initial renders of the login and dashboard page
- Azure Static Web App configurations for a live environment

Portal 932/release 0.1.0

---

README.md
package.json

Main README documentation for using and developing this application.

Portal 1012/readme docs

---

package.json
src/Dashboard.tsx
src/Landing.tsx
src/main.tsx
src/styles/Landing.module.css
yarn.lock

- Allows for user session storage in the auth provider
- Allows refresh, but still maintains session context

Added web storage to auth provider config

---

src/App.tsx
src/Dashboard.tsx
src/Logout.tsx
src/components/ProtectedRoute.tsx
src/main.tsx
tests/Dashboard.test.tsx
tests/helpers.tsx

- Adds a logout route
- Onclick of Logout section of sidebar
- Maintains ability for logout to be a loading page

PORTAL-1005: Add logout route

---

.gitignore
package.json
playwright.config.ts
tests/e2e/landing.spec.ts
tests/e2e/utils.ts
vite.config.ts
yarn.lock

Initial config and test set for Playwright e2e tests.

Portal 1022/playwrite sandbox

---

package.json
yarn.lock

Update cdc-react and cdc-react-icon package versions to include bug fixes from those packages.

bump package versions

---

.github/workflows/deploy.yml
playwright.config.ts
tests/e2e/landing.spec.ts

Runs Playwright tests in CD pipeline after app deployment.

Portal 1069/e2e in cd pipeline

---

api/src/functions/token.ts
src/main.tsx

Testing steps:
1. Setup dev environment
2. Run `yarn simulate`
3. Navigate to localhost:4280
4. Login with sams
5. Inspect your session storage and verify the "scope" property has "dex:status openid profile email" as its value.

scopes for token and user info requests

---

upload-tool/App.tsx

Portal-1315/Add Metadata Fields

---

upload-tool/App.tsx

* Revert dropdowns to be aligned with v1 metadata
* Update API call to use v1 metadata keys

Portal 1345/update metadata

---

upload-tool/App.tsx

* Small enhancement to add feedback to the page when an upload is submitted

Upload tool: add basic feedback

---

upload-tool/App.tsx

Add new requested metadata fields.

Portal-1350/add new metadata fields

---

package.json
src/App.tsx
src/Shell.tsx
src/Submissions.tsx
tests/Submissions.test.tsx
yarn.lock

* Adds table component to file submission page
* Updates cdc-react-icons to 2.2.0

Portal 1323/file submission table

---

.github/workflows/app-service-dev.yml
.github/workflows/remote-trigger-template.yml

- Added github action template for remote trigger

Added remote trigger workflow

---

.eslintrc.cjs
src/App.tsx
upload-tool/App.tsx
upload-tool/styles.css

- Adds additional metadata fields
- Updates event options based-off destination selection

PORTAL-1399: upload tool updates

---

.github/workflows/deploy_dev.yml
README.md
src/config/api.ts
src/main.tsx
staticwebapp.config.json

- updates workflow to deploy frontend code to SWA
- updates README.md

update: dev deployment workflow for SWA

---

package.json
yarn.lock

updates packages to fix the high severity issues listed in `yarn audit`
Will/should alleviate both dependabot PRs

updates pkgs to resolve all high-severity vulns

---

api/src/main/kotlin/com/dexportalapi/DeXPortalAPI/web/MainController.kt
src/App.tsx
src/components/PieChart.tsx
src/components/StatusBoxes.tsx
src/mocks/data/reportCounts.json
src/screens/Dashboard.tsx
src/utils/api/reportCounts.ts
src/utils/helperFunctions/statusDisplayValues.ts
tests/unit/components/StatusBoxes.test.tsx
tests/unit/utils/helperFunctions/statusDisplayValues.test.ts

- Call updated PS API counts endpoint
- checking the portal counts API JSON structure matches PS API
- Update mocs
- Update PieChart and StatusBoxes components to handle new structure
Connected to this ticket:  https://cdc-dexops.atlassian.net/browse/PORTAL-1488

Portal 1488/connect to counts endpoint

---

api/src/main/kotlin/com/dexportalapi/DeXPortalAPI/web/MainController.kt
api/src/test/kotlin/com/dexportalapi/DeXPortalAPI/DeXPortalApiApplicationTests.kt
src/screens/Submissions.tsx
src/styles/_shared.scss

- make params optional for reportCoutns endpoint
- avoid abundant calls to auth code endpoint
- add index endpoint

update: adjust for optional params /reportCounts endpoint

---

src/App.tsx
src/components/PieChart.tsx
src/components/StatusBoxes.tsx
src/mocks/data/reportCounts.json
src/utils/api/reportCounts.ts
src/utils/helperFunctions/statusDisplayValues.ts
tests/unit/components/StatusBoxes.test.tsx
tests/unit/utils/api/reportCounts.test.ts
tests/unit/utils/helperFunctions/statusDisplayValues.test.ts

Connected to ticket: [Portal-1499](https://cdc-dexops.atlassian.net/browse/PORTAL-1499)
* Match current figma naming schemes (Failed, Complete, Processing)
* update the catch case for no data - fix NAN’s
* update mocks and discuss with PS-API to update on their end

Updated naming conventions and fixed NAN's

---

package.json
tests/e2e/landing.spec.ts
tests/utility/utils.ts
yarn.lock

- adds a 508 compliance helper utility to be utilized for each page navigated to
- added first check to e2e tests
Notes:
- We will utilize this utility once test credentials are created and updated.  
- We will need to add these to existing/future e2e tests

PORTAL-1511: 508 Compliance Check 

---

package.json
yarn.lock

Updated Package.json and yarn.lock to reflect cdc-react changes.

Updating packages

---

src/components/ProtectedRoute.tsx

Ignore auth if running locally.

Ignore auth if running locally

---

.github/workflows/deploy_dev.yml
.github/workflows/deploy_stg.yml

* Added specific environments for Dev, Test, Stage, Prod
* Added environment specific secret for App_Config_ConnectionString
* Added env var to github action files

Updated github action files

---

src/screens/Dashboard.tsx

Console log adjusted for super user feature flag

Console log adjusted for super user feature flag

---

src/screens/Dashboard.tsx

Reverting changes to see if Auth works on dex dev after deployment.

Reverted changes

---

package.json
src/components/DetailsModal.tsx
yarn.lock

Moved file title above Status Pill in the details modal in accordance to the current figmas: 
https://www.figma.com/file/TrW6WMf6GYgscPkVQaiMZ0/CDC-React-Components?type=design&node-id=76-4280&mode=design&t=W5yaKGqegbHIhzfr-0

Small ui update

---

api/src/main/kotlin/com/dexportalapi/DeXPortalAPI/web/MainController.kt

- revert changes from backend, worked locally, but doesn't on deploy
- looking further into issue

fix: rollback backend

---

package.json
src/screens/Dashboard.tsx
src/screens/Submissions.tsx
src/types/timeframes.ts
src/utils/api/fileSubmissions.ts
src/utils/api/reportCounts.ts
src/utils/helperFunctions/date.ts
tests/unit/utils/helperFunctions/date.test.ts
yarn.lock

Connect to this ticket: https://cdc-dexops.atlassian.net/browse/PORTAL-1666
- added Routes to Track Submissions Page
- added DataStream, Routes, and Timeframe to Dashboard
- added getPastDate help function and tests
- added Enum and Static values for Timeframes

Portal 1666/add dropdowns

---

api/src/main/kotlin/com/dexportalapi/DeXPortalAPI/utils/DateUtils.kt
api/src/main/kotlin/com/dexportalapi/DeXPortalAPI/web/MainController.kt
api/src/test/kotlin/com/dexportalapi/DeXPortalAPI/DateUtilsTests.kt
api/src/test/kotlin/com/dexportalapi/DeXPortalAPI/utils/DateUtilsTests.kt

* Adds util to convert iso datestring to PS API required date format
* Updates calls to PS API to use new util for date conversion

Portal 1676/convert iso date for psapi

---

src/App.tsx
src/mocks/data/dataStreams.ts
src/mocks/handlers/mmsHandlers.ts
src/screens/MetadataManagement.tsx
src/screens/Shell.tsx
src/utils/api/dataStreams.ts
src/utils/api/entities.ts
src/utils/api/manifests.ts
src/utils/api/programs.ts
src/utils/api/routes.ts
src/utils/helperFunctions/jsonPrettyPrint.tsx
tests/unit/utils/api/dataStreams.test.ts

GUI for Metadata Management in Portal React app
- Entities
- Programs
- Datastreams
- Routes
- Manifests

Portal 1716/MMS_GUI

---

api/src/main/kotlin/dexportal/routes/psApi/SubmissionDetails.kt
src/components/DetailsModal.tsx
src/components/PieChart.tsx
src/components/StatusBoxes.tsx
src/mocks/data/fileSubmissions.ts
src/mocks/data/reportCounts.ts
src/mocks/data/submissionDetails.ts
src/screens/Dashboard.tsx
src/screens/Submissions.tsx
src/types/timeframes.ts
src/utils/api/fileSubmissions.ts
src/utils/api/reportCounts.ts
src/utils/api/submissionDetails.ts
src/utils/helperFunctions/date.ts
src/utils/helperFunctions/statusDisplayValues.tsx
tests/unit/components/StatusBoxes.test.tsx
tests/unit/utils/helperFunctions/statusDisplayValues.test.ts

Updating the mocks and front end management of PS-API data to mimic what is currently returned from PS-API.

Portal 1731/ps api frontend updates

---

.github/workflows/app-service-dev.yml

Updating deployment file for api

Deployment update

---

package.json
src/App.css
src/components/Table.tsx
src/mocks/data/fileSubmissions.ts
src/screens/Submissions.tsx
yarn.lock

Related to the following tickets: 
https://cdc-dexops.atlassian.net/browse/PORTAL-1752
https://cdc-dexops.atlassian.net/browse/PORTAL-1324
Adding sorting and pagination `getFileSubmissions`

Portal 1324 & 1752:  sort submissions and pagination

---

.github/workflows/app-service-dev.yml
.github/workflows/deploy_dev.yml
.github/workflows/deploy_stg.yml
.github/workflows/deploy_tst.yml
package.json

- Fixed workflow errors for tst environment frontend deployment
- Renamed workflows for clarity & consistency

Fixes for tst workflow

---

.github/workflows/deploy_dev.yml
api/src/main/kotlin/dexportal/routes/psApi/FileSubmissions.kt

Pass Page_Size parameter through to PS-API for file submissions call.

Add page size to submissions

---

src/components/Button.tsx
src/components/table/Pagination.tsx
src/components/table/Table.tsx
src/mocks/data/fileSubmissions.ts
src/screens/Submissions.tsx
src/styles/PieChart.module.css
src/styles/Table.module.css
tests/unit/components/Button.test.tsx
tests/unit/components/table/Pagination.test.tsx

- Add custom paginator component
- has first and last page, and allows for overflow
- tests added

Portal 1792/paginator refactor

---

src/screens/UploadFiles.tsx
tests/unit/screens/UploadFiles.test.tsx
yarn.lock

Adds test to upload files page
Updates Submit button to be disabled until form is complete

Upload files page updates + tests

---

src/screens/UploadFiles.tsx

* Updates upload page to show a "Starting..." message when Submit is clicked
* Disables "Submit" button when an upload is in-progress

Portal-1872 initial upload feedback
